"""empty message

Revision ID: 1448c842806d
Revises: 13b4704671c8
Create Date: 2026-06-18 18:52:50.349107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1448c842806d'
down_revision = '13b4704671c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accessibility_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('osm_id', sa.String(length=50), nullable=False),
    sa.Column('osm_type', sa.String(length=10), nullable=False),
    sa.Column('place_name', sa.String(length=200), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('wheelchair', sa.String(length=10), nullable=True),
    sa.Column('has_ramp', sa.Boolean(), nullable=True),
    sa.Column('has_elevator', sa.Boolean(), nullable=True),
    sa.Column('has_accessible_toilet', sa.Boolean(), nullable=True),
    sa.Column('has_accessible_parking', sa.Boolean(), nullable=True),
    sa.Column('automatic_door', sa.Boolean(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('accessibility_reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accessibility_reviews_osm_id'), ['osm_id'], unique=False)

    op.create_table('accessibility_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('caption', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['accessibility_reviews.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('accessibility_photos')
    with op.batch_alter_table('accessibility_reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accessibility_reviews_osm_id'))

    op.drop_table('accessibility_reviews')
    # ### end Alembic commands ###
