"""empty message

Revision ID: 2105db44f4c9
Revises: c6a6a0cbfd98
Create Date: 2026-06-25 17:34:08.208134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2105db44f4c9'
down_revision = 'c6a6a0cbfd98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip_day_places', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visit_time', sa.Time(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip_day_places', schema=None) as batch_op:
        batch_op.drop_column('visit_time')

    # ### end Alembic commands ###
