"""empty message

Revision ID: 5126b6cc3efc
Revises: e5fe8ea502df
Create Date: 2026-06-27 03:08:41.258110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5126b6cc3efc'
down_revision = 'e5fe8ea502df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trip_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_user_favorites_trip_id', 'trips', ['trip_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_favorites', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_favorites_trip_id', type_='foreignkey')
        batch_op.drop_column('trip_id')

    # ### end Alembic commands ###
