"""empty message

Revision ID: 7af55c5e57df
Revises: 2105db44f4c9
Create Date: 2026-06-25 17:57:54.280280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7af55c5e57df'
down_revision = '2105db44f4c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip_day_places', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visit_time_end', sa.Time(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip_day_places', schema=None) as batch_op:
        batch_op.drop_column('visit_time_end')

    # ### end Alembic commands ###
