"""empty message

Revision ID: 9c6fb1b06dce
Revises: 5126b6cc3efc
Create Date: 2026-06-27 17:21:19.570371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c6fb1b06dce'
down_revision = '5126b6cc3efc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('place_label', sa.String(length=100), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_user_favorites_trip_id'), type_='foreignkey')
        batch_op.drop_column('trip_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trip_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_user_favorites_trip_id'), 'trips', ['trip_id'], ['id'])
        batch_op.drop_column('place_label')

    # ### end Alembic commands ###
