"""empty message

Revision ID: cc2f225ab1bc
Revises: 7fef9f26196c
Create Date: 2026-06-24 12:44:12.724588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc2f225ab1bc'
down_revision = '7fef9f26196c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wheelchair', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('osm_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('sub_type', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('all_tags', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_favorites', schema=None) as batch_op:
        batch_op.drop_column('all_tags')
        batch_op.drop_column('sub_type')
        batch_op.drop_column('osm_type')
        batch_op.drop_column('wheelchair')

    # ### end Alembic commands ###
